// The Master Song List: Song Title (key) and Artist (value)
// Use the tags 'cat1', 'cat2', 'cat3' for your lists.
const SONG_DATA = {
    
    // --- CATEGORY 1: Classic Rock Relaxation (77 Songs) - Tag: 'cat1' ---
    "#9 Dream": { artist: "John Lennon", genres: ["cat1", "70s", "pop", "rock"] },
    "A Horse with No Name": { artist: "America", genres: ["cat1", "70s", "rock", "pop"] },
    "A Pillow of Winds": { artist: "Pink Floyd", genres: ["cat1", "70s", "rock"] },
    "Angie (Remastered 2009)": { artist: "The Rolling Stones", genres: ["cat1", "70s", "rock"] },
    "Beast Of Burden (Remastered 1994)": { artist: "The Rolling Stones", genres: ["cat1", "70s", "rock"] },
    "Bell Bottom Blues": { artist: "Derek & The Dominos", genres: ["cat1", "70s", "rock"] },
    "Black Water": { artist: "The Doobie Brothers", genres: ["cat1", "70s", "rock", "pop"] },
    "Blackbird (Remastered 2009)": { artist: "The Beatles", genres: ["cat1", "60s", "pop"] },
    "California Dreamin' (Single Version)": { artist: "The Mamas & The Papas", genres: ["cat1", "60s", "pop"] },
    "Can't Find My Way Home": { artist: "Blind Faith", genres: ["cat1", "60s", "rock"] },
    "Crazy Love (Van Morrison)": { artist: "Van Morrison", genres: ["cat1", "70s", "pop"] },
    "Crazy Love (Poco)": { artist: "Poco", genres: ["cat1", "70s", "rock", "pop"] },
    "Dark Sweet Lady": { artist: "George Harrison", genres: ["cat1", "70s", "pop"] },
    "Deacon Blues": { artist: "Steely Dan", genres: ["cat1", "70s", "rock", "pop"] },
    "Dirty Work": { artist: "Steely Dan", genres: ["cat1", "70s", "rock", "pop"] },
    "Does Anybody Really Know What Time It Is?": { artist: "Chicago", genres: ["cat1", "70s", "rock"] },
    "Dog & Butterfly": { artist: "Heart", genres: ["cat1", "70s", "rock"] },
    "Dreams (2004 Remaster)": { artist: "Fleetwood Mac", genres: ["cat1", "70s", "rock", "pop"] },
    "Everybody's Talkin' (From 'Midnight Cowboy')": { artist: "Harry Nilsson", genres: ["cat1", "60s", "pop"] },
    "Fearless": { artist: "Pink Floyd", genres: ["cat1", "70s", "rock"] },
    "For What It's Worth": { artist: "Buffalo Springfield", genres: ["cat1", "60s", "rock"] },
    "From Now On": { artist: "Supertramp", genres: ["cat1", "70s", "pop", "rock"] },
    "From the Beginning": { artist: "Emerson, Lake & Palmer", genres: ["cat1", "70s", "rock"] },
    "God Only Knows (Mono)": { artist: "The Beach Boys", genres: ["cat1", "60s", "pop"] },
    "Going to California (Remaster)": { artist: "Led Zeppelin", genres: ["cat1", "70s", "rock"] },
    "Goodbye Yellow Brick Road": { artist: "Elton John", genres: ["cat1", "70s", "pop"] },
    "Graceland": { artist: "Paul Simon", genres: ["cat1", "80s", "pop"] },
    "Hello It's Me": { artist: "Todd Rundgren", genres: ["cat1", "70s", "pop"] },
    "I’ll Have to Say I Love You in a Song": { artist: "Jim Croce", genres: ["cat1", "70s", "pop"] },
    "I'm Not In Love": { artist: "10cc", genres: ["cat1", "70s", "pop"] },
    "If You Could Read My Mind": { artist: "Gordon Lightfoot", genres: ["cat1", "70s", "pop"] },
    "In My Life (Remastered 2009)": { artist: "The Beatles", genres: ["cat1", "60s", "pop"] },
    "It's Too Late": { artist: "Carole King", genres: ["cat1", "70s", "pop"] },
    "Knockin' On Heaven's Door": { artist: "Bob Dylan", genres: ["cat1", "70s", "pop"] },
    "Lady Stardust": { artist: "David Bowie", genres: ["cat1", "70s", "pop", "rock"] },
    "Lay, Lady, Lay": { artist: "Bob Dylan", genres: ["cat1", "60s", "pop"] },
    "Let 'Em In": { artist: "Paul McCartney & Wings", genres: ["cat1", "70s", "pop"] },
    "Let It Be (Remastered 2009)": { artist: "The Beatles", genres: ["cat1", "70s", "pop"] },
    "Lotta Love": { artist: "Nicolette Larson", genres: ["cat1", "70s", "pop"] },
    "Mona Lisas And Mad Hatters": { artist: "Elton John", genres: ["cat1", "70s", "pop"] },
    "My Sweet Lord": { artist: "George Harrison", genres: ["cat1", "70s", "pop"] },
    "Never Going Back Again (2004 Remaster)": { artist: "Fleetwood Mac", genres: ["cat1", "70s", "rock", "pop"] },
    "On And On": { artist: "Stephen Bishop", genres: ["cat1", "70s", "pop"] },
    "Ooh La La": { artist: "Faces", genres: ["cat1", "70s", "rock"] },
    "Our House": { artist: "Crosby, Stills, Nash & Young", genres: ["cat1", "70s", "pop"] },
    "Peaceful Easy Feeling": { artist: "Eagles", genres: ["cat1", "70s", "rock"] },
    "Pink Moon": { artist: "Nick Drake", genres: ["cat1", "70s", "pop"] },
    "Right Down the Line": { artist: "Gerry Rafferty", genres: ["cat1", "70s", "pop"] },
    "Ripple": { artist: "Grateful Dead", genres: ["cat1", "70s", "rock"] },
    "Sara": { artist: "Fleetwood Mac", genres: ["cat1", "70s", "rock", "pop"] },
    "Sara Smile": { artist: "Daryl Hall & John Oates", genres: ["cat1", "70s", "pop"] },
    "Scarborough Fair / Canticle": { artist: "Simon & Garfunkel", genres: ["cat1", "60s", "pop"] },
    "She's Always a Woman": { artist: "Billy Joel", genres: ["cat1", "70s", "pop"] },
    "She's Gone": { artist: "Daryl Hall & John Oates", genres: ["cat1", "70s", "pop"] },
    "Slip Slidin' Away": { artist: "Paul Simon", genres: ["cat1", "70s", "pop"] },
    "Something (Remastered 2009)": { artist: "The Beatles", genres: ["cat1", "60s", "pop"] },
    "Something in the Way She Moves": { artist: "James Taylor", genres: ["cat1", "70s", "pop"] },
    "Summer Breeze": { artist: "Seals and Crofts", genres: ["cat1", "70s", "pop"] },
    "Teach Your Children": { artist: "Crosby, Stills, Nash & Young", genres: ["cat1", "70s", "pop"] },
    "Thank You (Remaster)": { artist: "Led Zeppelin", genres: ["cat1", "70s", "rock"] },
    "The Air That I Breathe (2008 Remaster)": { artist: "The Hollies", genres: ["cat1", "70s", "pop"] },
    "The Long And Winding Road (2021 Mix)": { artist: "The Beatles", genres: ["cat1", "70s", "pop"] },
    "The Only Living Boy in New York": { artist: "Simon & Garfunkel", genres: ["cat1", "70s", "pop"] },
    "The Sound of Silence (Electric Version)": { artist: "Simon & Garfunkel", genres: ["cat1", "60s", "pop"] },
    "The Weight (Remastered 2000)": { artist: "The Band", genres: ["cat1", "60s", "rock"] },
    "Tin Man": { artist: "America", genres: ["cat1", "70s", "rock", "pop"] },
    "Tuesday's Gone": { artist: "Lynyrd Skynyrd", genres: ["cat1", "70s", "rock"] },
    "Undun (2024 Remaster)": { artist: "The Guess Who", genres: ["cat1", "60s", "rock"] },
    "Waterloo Sunset": { artist: "The Kinks", genres: ["cat1", "60s", "pop"] },
    "We Just Disagree": { artist: "Dave Mason", genres: ["cat1", "70s", "pop"] },
    "We've Got Tonight": { artist: "
